In [ ]:
#Ques 1




In [2]:
import numpy as np
m = np.array([1,2,3])
n = np.array([4,5,6])



In [29]:
print(np.greater(m, n))

[False False False]


In [30]:
print(np.greater_equal(m,n))

[False False False]


In [31]:
print(np.less(m,n))

[ True  True  True]


In [32]:
print(np.less_equal(m,n))

[ True  True  True]


In [38]:
#Ques 2




In [39]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [40]:
#Ques3




In [43]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
#Ques4




In [59]:
x = np.arange(21)
print("Original Vector")
print(x)
print("Vector after Changing")
x[(x>=9) & (x<=15)]*=-1
print(x)

Original Vector
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Vector after Changing
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [61]:
#Ques 5




In [14]:
d = np.zeros((5,5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
None


In [18]:
np.fill_diagonal(d, [1, 2, 3, 4, 5])
print(d)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [20]:
#Ques 6




In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr))

45


In [54]:
print(np.sum(arr, axis=0)) #column wise sum 

[12 15 18]


In [38]:
print(np.sum(arr, axis=1)) #row wise sum

[ 6 15 24]


In [44]:
#Ques 7




In [45]:
a = np.array([1,2,3])
np.savetxt('file.txt',a)

In [46]:
#Ques 8




In [71]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
# np.all(a == b)
if np.array_equal(a, b):
    print("Equal")
else:
    print("Not Equal")


Equal


In [52]:
#Ques 9




In [62]:
arr = np.random.randint(1,10,(4,4))
print("Before swapping")
print(arr)
arr[[0,-1]] = arr[[-1, 0]]
print("After swapping")
print(arr)

Before swapping
[[9 4 5 1]
 [8 5 9 3]
 [8 5 9 1]
 [5 7 2 5]]
After swapping
[[5 7 2 5]
 [8 5 9 3]
 [8 5 9 1]
 [9 4 5 1]]


In [63]:
#Ques 10




In [67]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6],[4,5,6]])
np.multiply(a,b)

array([[ 4, 10, 18],
       [ 4, 10, 18],
       [ 4, 10, 18]])