In [6]:
import numpy as np
a=[[],[],[]]
b=[[],[],[]]

print("Enter 1st matrix")
for i in range(3):
    for j in range(3):
        a[i].append(int(input()))

print("Enter 2nd matrix")
for i in range(3):
    for j in range(3):
        b[i].append(int(input()))

print(a)
print(b)

Enter 1st matrix


 1
 2
 3
 4
 5
 6
 7
 8
 9


Enter 2nd matrix


 11
 12
 13
 14
 15
 16
 17
 18
 19


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [8]:
a=np.array(a)
b=np.array(b)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [10]:
np.dot(a,b)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [11]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
b.T

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [14]:
a.trace()

15

In [15]:
b.trace()

45

In [17]:
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [20]:
np.linalg.matrix_rank(a)

2

In [21]:
np.linalg.matrix_rank(b)

2

In [22]:
np.linalg.det(a)

6.66133814775094e-16

In [23]:
np.linalg.det(b)

-1.5987211554602137e-14

In [24]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [26]:
np.linalg.eig(a)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))